### ISSUE TITLE
How do I map this to an actual repo/file?

### ISSUE THREAD

**Issue by wmacevoy** [jonschlinkert/get-file#3]
Ok, so I want to get 

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

I would like to put this in a howto in a portable way using your get-file.  How do I get this file and how does your readme help me interpret this URL into your CLI/API syntax?

**Comment by doowb** [comment]
> How do I get this file

You should be able to do this in the CLI:

``` sh
$ get-file github/gitignore Global/JetBrains.gitignore
```

Looks like there's an error when writing the file to a subdirectory that doesn't exist yet. (I created issue #4 for this)

API usage:

``` js
var client = require('get-file');

// `getFile` takes "user/repo", "path to file", and callback
client.getFile('github/gitignore', 'Global/JetBrains.gitignore', function (err, res) {
  if (err) return console.error(err);

  // `res` is a stream that you can pipe into another filestream
  var file = fs.createWriteStream('JetBrains.gitignore');
  res.pipe(file);
});
```

**Comment by wmacevoy** [comment]
So the branch just doesn't figure in?  Master seems like a great default.  I kept trying to put it in there.  Thanks!

Warren MacEvoy
wmacevoy@coloradomesa.edu
http://www.coloradomesa.edu/~wmacevoy
970-248-1070

**Comment by jonschlinkert** [comment]
closing, sounds like this was resolved
